name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install system deps
        run: sudo apt-get update && sudo apt-get install -y libxkbcommon-x11-0 libxcb-cursor0
      - name: Install dependencies
        working-directory: flowproc-project
        run: |
          python -m pip install --upgrade pip
          pip install .[dev]
      - name: Lint and type check
        working-directory: flowproc-project
        run: |
          flake8 flowproc tests
          mypy flowproc
      - name: Run tests
        working-directory: flowproc-project
        env:
          QT_QPA_PLATFORM: offscreen
        run: pytest -q